config/routes.rb
Rails.application.routes.draw do
  resources :users, :forums, :comments, :discussions
  
  resources :discussions, only: [:show] do
    resources :comments
  end
 
  root to: "home#index"

  get 'sessions/new'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'


  get '/auth/facebook/callback' => 'sessions#create'
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :forum
    belongs_to :user
    has_many :comments, dependent: :destroy
    
    scope :recent, -> { order(created_at: :desc) }

    validates :title, :content, presence: true
    resourcify
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :find_forums, only: [:index, :show, :new, :edit]

  def index
    @discussions = Discussion.recent.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    render :show
  end

  def new
    @discussion = Discussion.new()
  end

  def edit
  end

  def create
    @discussion = current_user.discussions.build(discussion_params)

    if @discussion.save
      redirect_to @discussion, flash:{notice: "Discussion created!"}
    else
      redirect_to new_discussion_path, flash:{notice: "Please complete all fields."}
    end
  end

  def update
    if @discussion.update(discussion_params)
      redirect_to @discussion, flash:{notice: "Discussion updated."}
    else
      redirect_to edit_discussion_path, flash:{notice: "Please complete all fields."}
    end
  end

  def destroy
    @discussion.destroy
    redirect_to root_path, flash:{notice: "Discussion deleted."}
  end

  private

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
  
  def find_forums
    @forums = Forum.all.order('created_at desc')
  end

  def discussion_params
    params.require(:discussion).permit(:title, :content, :forum_id, :user_id)
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
    def discussion_author(discussion)
        signed_in? && current_user.id == discussion.user_id
    end
      
    def comment_author(comment)
        signed_in? && current_user.id == comment.user_id
    end
end

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
    <%= f.input :title, required: true, input_html: { class: 'input' }, label_html: { class: "label" } %>

    <%= f.input :content, required: true, input_html: { class: 'textarea' }, label_html: { class: "label" } %>
        
    <label class="label">Forum <i class="far fa-comments"></i></label>
        <div class="control">
            <span class="select">
                <%= f.input_field :forum_id, required: true, collection:@forums.map { |frm| [frm.forum_name, frm.id] }%>
            </span>
            <span class="icon is-small is-left">
                <i class="fa fa-tag"></i>
            </span>
        </div>
        <br>

    <%= f.button :submit, class: "btn btn-primary" %>
                    
<% end %>

app/views/discussions/edit.html.erb
<div class="content">

    <% if discussion_author(@discussion) || has_role?(:admin) || has_role?(:moderator) %>

        <h1>Edit Discussion</h1>
        <%= link_to "Back", @discussion %>
        <hr>
        <%= render 'form' %>

    <% else %>
        <p>You are not authorized to view this page</p>
    <% end %>

</div>

app/views/discussions/index.html.erb
<div class="content-sm">
  <h2>All Discussions</h2>
  <hr>
  <div>
    <% @discussions.each do |discussion| %>
      <div>
        <div>
          <%= link_to discussion do %>
            <h3><%= discussion.title %></h3>
            
          <% end %>
          <div>
            <p><em><small>Posted <%= discussion.created_at.strftime("%A, %B %e, %Y") %> in
              <% if discussion.forum %>
                <%= link_to discussion.forum.forum_name, discussion.forum %>
              <% end %>
              by <%= discussion.user.username %>
              </small>
              </em>
            </p>
          </div>
        </div>

      </div>
    <% end %>
    <div class="d-flex flex-row justify-content-center p-3">
        <%= will_paginate @discussions, class: 'p-3' %>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<div class="content">
    <h2>New Discussion</h2>
    <hr>
    <%= render 'form' %>

</div>

app/views/discussions/show.html.erb
<div class="content">
    <h1><%= @discussion.title %></h1>
    <h4>Forum: <%= link_to @discussion.forum.forum_name, @discussion.forum %></h4>

    <h5>by <%= link_to @discussion.user.username, @discussion.user %></h5>
    <%= @discussion.created_at.strftime("%A, %B %e, %Y") %> 
    <p class="discussion"><%= @discussion.content %></p>

    <% if discussion_author(@discussion) || has_role?(:admin) || has_role?(:moderator) %>
        <div>
          <%= link_to " Edit", edit_discussion_path(@discussion), class: 'btn btn-secondary far fa-edit' %> |
          <%= link_to " Delete", discussion_path(@discussion), method: :delete, data: { confirm: "Are you sure you want to delete this discussion?" }, class: 'btn btn-danger far fa-trash-alt' %>
        </div>
    <% end %>
    <br>
    
    <hr>

    <hr>

    <h5>This discussion has <%= @discussion.comments.count %> <%= link_to "comments", discussion_comments_path(@discussion) %></h5>
   
</div>