config/routes.rb
Rails.application.routes.draw do
  resources :users, :forums, :comments, :discussions
  
  resources :discussions, only: [:show] do
    resources :comments
  end
 
  root to: "home#index"

  get 'sessions/new'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'


  get '/auth/facebook/callback' => 'sessions#create'
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :discussion
    belongs_to :user
    validates :content, presence: true
    resourcify
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index 
    @discussion = Discussion.find(params[:discussion_id])
    @comments = @discussion.comments
  end

  def create
    @comment = current_user.comments.build(comment_params)
    
    @comment.user_id = current_user.id
    
    if @comment.valid?
      @comment.save
      redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Comment created!"}
    else
      redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Content field empty cannot be empty."}
    end
  end

  def edit
    @discussion = Discussion.find_by(params[:id])
    @comment = Comment.find(params[:id])
  end

  def show 
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.valid? 
      @comment.update(comment_params)
      redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Comment updated."}
    else
      redirect_to edit_comment_path, flash:{notice: "Content field cannot be empty."}
    end
  end

  def destroy
     @comment = Comment.find(params[:id])
     @comment.destroy
     redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Comment deleted."}
    
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :username, :discussion_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<h1>Leave a Comment</h1>

<%= simple_form_for @discussion.comments.build do |f| %>
  <%= f.hidden_field :discussion_id %>
  <%= f.hidden_field :user_id %>
  
  <div>
    <%= f.input :content, input_html: { class: 'textarea' }, label_html: { class: 'label' } %>
  </div>


<%= f.button :submit, 'Submit', class:'btn btn-info' %>

<% end %>

app/views/comments/edit.html.erb
<div class="content">

<% if comment_author(@comment) || has_role?(:admin) || has_role?(:moderator) %>

  <%= simple_form_for @comment do |f| %>
    <h1>Edit Comment</h1>
    <%= link_to "Back", discussion_comments_path(@comment.discussion) %>
    <hr>
    <%= f.input :content, input_html: { class: 'textarea' }, label_html: { class: 'label' } %>
    <%= f.button :submit, 'Update Comment', class:'btn btn-primary' %> 
  <% end %>

<% else %>
  <p>You are not authorized to view this page</p>
<% end %>

</div>

app/views/comments/index.html.erb
<div class="content">

<% if signed_in? %>
      <%= render 'comments/form' %>
    <% else %>
      <p>You need to <%= link_to 'sign in', signin_path %> to leave a comment. Don't have an account?
      <%= link_to 'Sign up', signup_path %> for one.</p>
    <% end %>

<br>

<%= link_to "Return to Discussion", discussion_path(@discussion), class: "btn btn-primary" %>

<br><br>

<% @comments.each do |comment|%>
        <% if @discussion.comments.count === 0 %>
          <p>Be the first to post a comment!</p>
        <% elsif comment.content != nil %>
          <div class="comment">
            <p>By <%= link_to comment.user.username, comment.user %> on <%= comment.created_at.strftime("%A, %B %e, %Y") %></p>
            <p><%= comment.content %></p>
              <% if comment_author(comment) || has_role?(:admin) || has_role?(:moderator) %>
                <%= link_to " Edit", edit_comment_path(comment), class: 'btn btn-secondary far fa-edit' %> |
                <%= link_to " Delete", [comment], method: :delete, data: {confirm: "Are you sure you want to delete this comment?" }, class: 'btn btn-danger far fa-trash-alt' %>
              <% end %>
          </div>
        <% end %>   
<% end %>  

</div>