config/routes.rb
Rails.application.routes.draw do
  resources :users, :forums, :comments, :discussions
  
  resources :discussions, only: [:show] do
    resources :comments
  end
 
  root to: "home#index"

  get 'sessions/new'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'


  get '/auth/facebook/callback' => 'sessions#create'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @discussions = Discussion.recent.paginate(page: params[:page], per_page: 9)
        @forums = Forum.all
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="headline">
    <h1>Welcome to Tarheel Teachers!</h1>
    <h4>A Discussion Board for North Carolina Educators</h4>
</div>
    <div class="row mr-auto ml-auto">
        <div class="col-md-3">
            <div class="card mt-3">
                <div class="card-body">
                    <h2 class="card-header"><%= link_to "All Discussions", discussions_path %></h2>
                    <br>
                    <h2 class="card-header">Forums</h2>
                    <ul class="list-group">
                        <% @forums.alpha.each do |forum| %>   
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            <h5><%= link_to forum.forum_name, forum %></h5>
                            <span class="badge badge-pill"><%= forum.discussions.count %></span>
                            </li>  
                        <% end %>
                    </ul> 
                    <% if has_role?(:admin) %>
                    <br>
                        <%= link_to 'View Forums List', forums_path, class: 'btn btn-secondary' %>
                    <% end %>        
                </div>
                
            </div>
        </div>

        
        <div class="col-md-8">
            <h2>Latest Discussions</h2>
            <div class="row">
                <% @discussions.each do |discussion| %>
                <div class="col-md-4">
                    <div class="card mt-3 p-3">
                        <%= link_to discussion do %>
                            <h3><%= discussion.title %></h3>
                        <% end %>
                        <div>
                            <p><em><small>Posted <%= time_ago_in_words(discussion.created_at) %> ago in
                            <% if discussion.forum %>
                                <%= link_to discussion.forum.forum_name, discussion.forum %>
                            <% end %>
                            by <%= discussion.user.username %>
                            </small>
                            </em>
                            </p>
                        </div>
                    </div>

                </div>
                <% end %>
        </div>
    </div>