config/routes.rb
Rails.application.routes.draw do
  resources :users, :forums, :comments, :discussions
  
  resources :discussions, only: [:show] do
    resources :comments
  end
 
  root to: "home#index"

  get 'sessions/new'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'


  get '/auth/facebook/callback' => 'sessions#create'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   
    @user.roles.each { |role| send(role.name_to_symbol) }

    if @user.roles.size == 0
      can :read, :all 
    end
  end

  def moderator
    can :manage, Discussion
    can :manage, Comment
  end

  def admin
    can :manage, :all
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :discussion
    belongs_to :user
    validates :content, presence: true
    resourcify
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :forum
    belongs_to :user
    has_many :comments, dependent: :destroy
    
    scope :recent, -> { order(created_at: :desc) }

    validates :title, :content, presence: true
    resourcify
end

app/models/forum.rb
class Forum < ApplicationRecord
    has_many :discussions, dependent: :destroy
    has_many :users, through: :discussions
    has_many :comments, through: :discussions
    validates :forum_name, presence: true
    scope :alpha, -> { order(forum_name: :asc) }
    resourcify
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
    rolify
    has_secure_password

    has_many :discussions, dependent: :destroy
    has_many :forums, through: :discussions
    has_many :comments, dependent: :destroy

    validates :username, presence: true 
    validates :username, uniqueness: true
    validates :email, presence: true
    validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :password, presence: true, length: { minimum: 7  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :signed_in?

    before_action :initialize_user

    def initialize_user
      @user = User.new
    end

    def sign_in_required
        if !signed_in?
          redirect_to root_path, flash: {notice: "You must sign in first."}
        end
      end

    def signed_in?
        !!current_user
    end

    def current_user 
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index 
    @discussion = Discussion.find(params[:discussion_id])
    @comments = @discussion.comments
  end

  def create
    @comment = current_user.comments.build(comment_params)
    
    @comment.user_id = current_user.id
    
    if @comment.valid?
      @comment.save
      redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Comment created!"}
    else
      redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Content field empty cannot be empty."}
    end
  end

  def edit
    @discussion = Discussion.find_by(params[:id])
    @comment = Comment.find(params[:id])
  end

  def show 
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.valid? 
      @comment.update(comment_params)
      redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Comment updated."}
    else
      redirect_to edit_comment_path, flash:{notice: "Content field cannot be empty."}
    end
  end

  def destroy
     @comment = Comment.find(params[:id])
     @comment.destroy
     redirect_to discussion_comments_path(@comment.discussion_id), flash:{notice: "Comment deleted."}
    
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :username, :discussion_id, :content)
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :set_forum, only: [:show, :edit, :update, :destroy]

  def index
    @forums = Forum.all
  end

  def show
  end

  def new
    @forum = Forum.new
  end

  def edit
  end

  def create 
    @forum = Forum.new(forum_params)

    if @forum.save
      redirect_to forums_path, flash:{notice: "New forum created."}
    else
      redirect_to new_forum_path, flash:{notice: "Enter a forum name."}
    end
  end

  def update 
    if @forum.update(forum_params)
      redirect_to @forum, flash:{notice: "Forum name updated."}
    else
      redirect_to edit_forum_path, flash:{notice: "Enter a forum name."}
    end
  end

  def destroy
    @forum.destroy
    redirect_to forums_path, flash:{notice: "Forum deleted."}
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:forum_name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @discussions = Discussion.recent.paginate(page: params[:page], per_page: 9)
        @forums = Forum.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        if auth 
            if @user = User.find_by(:email => auth["info"]["email"])
              session[:user_id] = @user.id
              redirect_to root_path, flash:{notice: "You are now signed in."}
            else
              redirect_to 'users#new', flash:{alert: "User not found. Please sign up first."}
            end
          else
            @user = User.find_by(username: params[:user][:username])
            if @user && @user.authenticate(params[:user][:password])
              session[:user_id] = @user.id
              redirect_to root_path, flash:{notice: "You are now signed in."}
            else
              redirect_to signin_path, flash:{notice: "Invalid credentials. Please try again"}
            end
          end
    end

    def destroy
        session.clear
        redirect_to signin_path, flash:{notice: "You are now signed out."}
    end


    private

    def auth
        request.env['omniauth.auth']
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end 

    def show
        render :show
    end

    def edit
    end

    def create
        @user = User.new(user_params)
        if !@user.valid?
            redirect_to signup_path, flash:{notice: "Required input missing, or account with that username and/or email may already exist. Be sure password has at least 7 characters and that password fields match." }
        elsif @user.valid? && @user.save
            session[:user_id] = @user.id
            redirect_to @user, flash:{notice:"Account created. Thank you for joining Tarheel Teachers!"}
        end
    end

    def update
        if @user.update(user_params)
            redirect_to @user, flash:{notice: "Account info updated."}
        else
            redirect_to edit_user_path, flash:{notice: "Please complete all required fields. Be sure password fields match."}
        end
    end

    def destroy
        @user.destroy
        redirect_to root_path, flash:{notice: "Account has been deleted."}
    end
    
    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :bio, :quote)
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def has_role?(role)
        current_user && current_user.has_role?(role)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
    def discussion_author(discussion)
        signed_in? && current_user.id == discussion.user_id
    end
      
    def comment_author(comment)
        signed_in? && current_user.id == comment.user_id
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarheel Teachers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d34b6ee110.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
     
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark">
      <div class="brand-link">
        <%= link_to "Tarheel Teachers", root_path, class:"navbar-brand"%>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <%= link_to "Home", root_path, class:'nav-link' %>
              <% if signed_in? %>
                <%= link_to 'New Discussion', new_discussion_path, class:"nav-link" %>
                <%= link_to 'My Account', user_path(current_user), class: "nav-link" %>
                <%= link_to "Sign Out", signout_path, method: :delete , class:'nav-link' %>
              <% else %>
                <%= link_to "Sign In", signin_path, class:'nav-link' %>
                <%= link_to "Sign Up", signup_path, class:'nav-link' %>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <header>
      <h1>Tarheel Teachers</h1>
    </header>

     <p class="notice"><%= notice %></p>

    <%= yield %>

    <footer>
      <h4>&copy; 2020 Tarheel Teachers | contact@tarheelteachers.com | 888-111-2222</h4>
      <p>Images credit: <a href="https://www.pixabay.com" target="_blank">Pixabay</a></p>
    </footer>
  </body>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>